{
 "title": "NYC_Trips",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Question 1",
   "type": "singlestat",
   "description": "Qual a distância média percorrida por viagens com no máximo 2 passageiros:",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "lengthkm",
   "valueName": "avg",
   "targets": [
    { "rawSql": "SELECT 2.5" }
   ]
  },
  {
   "title": "Question 2",
   "type": "table",
   "description": "Quais os 3 maiores vendors em quantidade total de dinheiro arrecadado:",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT vendorId as CodigoVendor, vendorName as NomeVendor, dinheiroTotal as TotalArrecadado FROM question2"
    }
   ]
  },
  {
   "title": "Question 3",
   "type": "graph",
   "description": "Faça um histograma da distribuição mensal, nos 4 anos, de corridas pagas em dinheiro:",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "QuantidadeTotal" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  CONCAT(month, \"-\", RIGHT(year, 2)) as metric,\n  total as Quantidade\nFROM question3\nORDER BY year, month"
    }
   ]
  },
  {
   "title": "Question 4",
   "type": "graph",
   "description": "Faça um gráfico de série temporal contando a quantidade de gorjetas de cada dia, nos\núltimos 3 meses de 2012:",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Gorjeta" }
   ],
   "targets": [
    {
     "rawSql": "SELECT now() as time, CONCAT(day, \"/\", month) as metric, valorTotal as Gorjeta\nFROM question4\nORDER BY month, day"
    }
   ]
  },
  {
   "title": "Extra1",
   "type": "singlestat",
   "description": "Qual o tempo médio das corridas nos dias de sábado e domingo:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT tempoMedioSegundos FROM extra1\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Extra2",
   "type": "grafana-worldmap-panel",
   "description": "Fazer uma visualização em mapa com latitude e longitude de pickups e dropoffs no ano\nde 2010:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "(SELECT pickup_longitude as longitude, pickup_latitude as latitude, 10 as metric, \"Pickup\" as label\nFROM extra2\nLIMIT 100)\nUNION\n(SELECT dropoff_longitude as longitude, dropoff_latitude as latitude, -1 as metric, \"Dropoff\" as label\nFROM extra2\nLIMIT 100)"
    }
   ]
  },
  {
   "title": "Extra 3",
   "type": "grafana-worldmap-panel",
   "description": "Simular um streaming dos dados dos JSON e fazer uma visualização acompanhando umamétrica em tempo-real:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "(SELECT pickup_longitude as longitude, pickup_latitude as latitude, 10 as metric, \"Pickup\" as label\nFROM extra3\n)\nUNION\n(SELECT dropoff_longitude as longitude, dropoff_latitude as latitude, -1 as metric, \"Dropoff\" as label\nFROM extra3\n)\n"
    }
   ]
  }
 ]
}