version: '3'
services:
  zeppelin:
      image: apache/zeppelin:0.8.2
      ports: 
        - 8080:8080
        - 8443:8443
      # volumes:
      #   - spark-master-volume:/opt/zeppelin/logs
      #   - spark-master-volume:/opt/zeppelin/notebookcd
      environment:
        MASTER: "spark://spark-master:7077"
        SPARK_MASTER: "spark://spark-master:7077"
        SPARK_HOME: /usr/spark-2.4.1
      depends_on:
        - spark-master


  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 10.129.34.90
    volumes:
      - spark-master-volume:/conf
      - spark-master-volume:/tmp/data
    ports: 
      - 8000:8080